--------------------------------------------------------
-- Archivo creado  - jueves-julio-21-2022   
--------------------------------------------------------
DROP TABLE "SPRING"."CATEGORIAS" cascade constraints;
DROP TABLE "SPRING"."CLIENTES" cascade constraints;
DROP TABLE "SPRING"."COMUNA" cascade constraints;
DROP TABLE "SPRING"."DETALLE_VENTAS" cascade constraints;
DROP TABLE "SPRING"."EMPLEADOS" cascade constraints;
DROP TABLE "SPRING"."PRODUCTOS" cascade constraints;
DROP TABLE "SPRING"."REGIONES" cascade constraints;
DROP TABLE "SPRING"."SUCURSALES" cascade constraints;
DROP TABLE "SPRING"."VENTAS" cascade constraints;
--------------------------------------------------------
--  DDL for Table CATEGORIAS
--------------------------------------------------------

  CREATE TABLE "SPRING"."CATEGORIAS" 
   (	"IDCATEGORIA" NUMBER(5,0), 
	"NOMBRE" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "TBS_SPRING" ;
--------------------------------------------------------
--  DDL for Table CLIENTES
--------------------------------------------------------

  CREATE TABLE "SPRING"."CLIENTES" 
   (	"IDCLIENTE" NUMBER(5,0), 
	"NOMBRE" VARCHAR2(100 BYTE), 
	"APEPAT" VARCHAR2(100 BYTE), 
	"APEMAT" VARCHAR2(100 BYTE), 
	"IDCOMUNA" NUMBER(5,0), 
	"TELEFONO" VARCHAR2(100 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "TBS_SPRING" ;
--------------------------------------------------------
--  DDL for Table COMUNA
--------------------------------------------------------

  CREATE TABLE "SPRING"."COMUNA" 
   (	"IDCOMUNA" NUMBER(5,0), 
	"DESCRIPCION" VARCHAR2(100 BYTE), 
	"IDREGION" NUMBER(5,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "TBS_SPRING" ;
--------------------------------------------------------
--  DDL for Table DETALLE_VENTAS
--------------------------------------------------------

  CREATE TABLE "SPRING"."DETALLE_VENTAS" 
   (	"IDVENTA" NUMBER(5,0), 
	"IDPROCUTO" NUMBER(5,0), 
	"CANTIDAD" NUMBER(5,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "TBS_SPRING" ;
--------------------------------------------------------
--  DDL for Table EMPLEADOS
--------------------------------------------------------

  CREATE TABLE "SPRING"."EMPLEADOS" 
   (	"IDEMPLEADO" NUMBER, 
	"NOMBRE" VARCHAR2(100 BYTE), 
	"APEPAT" VARCHAR2(100 BYTE), 
	"APEMAT" VARCHAR2(100 BYTE), 
	"IDSUCURSAL" NUMBER(5,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "TBS_SPRING" ;
--------------------------------------------------------
--  DDL for Table PRODUCTOS
--------------------------------------------------------

  CREATE TABLE "SPRING"."PRODUCTOS" 
   (	"IDPRODUCTO" NUMBER(5,0), 
	"NOMBRE" VARCHAR2(100 BYTE), 
	"PRECIO" NUMBER(10,0), 
	"STOCK" NUMBER(10,0), 
	"IDCATEGORIA" NUMBER(5,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "TBS_SPRING" ;
--------------------------------------------------------
--  DDL for Table REGIONES
--------------------------------------------------------

  CREATE TABLE "SPRING"."REGIONES" 
   (	"IDREGION" NUMBER(5,0), 
	"DESCRICPION" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "TBS_SPRING" ;
--------------------------------------------------------
--  DDL for Table SUCURSALES
--------------------------------------------------------

  CREATE TABLE "SPRING"."SUCURSALES" 
   (	"IDSUCURSAL" NUMBER(5,0), 
	"DESCRIPCION" VARCHAR2(100 BYTE), 
	"IDCOMUNA" NUMBER(5,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "TBS_SPRING" ;
--------------------------------------------------------
--  DDL for Table VENTAS
--------------------------------------------------------

  CREATE TABLE "SPRING"."VENTAS" 
   (	"IDVENTA" NUMBER(5,0), 
	"IDEMPLEADO" NUMBER(5,0), 
	"IDCLIENTE" NUMBER(5,0), 
	"FECHA" DATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "TBS_SPRING" ;
REM INSERTING into SPRING.CATEGORIAS
SET DEFINE OFF;
REM INSERTING into SPRING.CLIENTES
SET DEFINE OFF;
REM INSERTING into SPRING.COMUNA
SET DEFINE OFF;
REM INSERTING into SPRING.DETALLE_VENTAS
SET DEFINE OFF;
REM INSERTING into SPRING.EMPLEADOS
SET DEFINE OFF;
REM INSERTING into SPRING.PRODUCTOS
SET DEFINE OFF;
REM INSERTING into SPRING.REGIONES
SET DEFINE OFF;
REM INSERTING into SPRING.SUCURSALES
SET DEFINE OFF;
REM INSERTING into SPRING.VENTAS
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index CATEGORIAS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SPRING"."CATEGORIAS_PK" ON "SPRING"."CATEGORIAS" ("IDCATEGORIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "TBS_SPRING" ;
--------------------------------------------------------
--  DDL for Index CLIENTES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SPRING"."CLIENTES_PK" ON "SPRING"."CLIENTES" ("IDCLIENTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "TBS_SPRING" ;
--------------------------------------------------------
--  DDL for Index COMUNA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SPRING"."COMUNA_PK" ON "SPRING"."COMUNA" ("IDCOMUNA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "TBS_SPRING" ;
--------------------------------------------------------
--  DDL for Index DETALLE_VENTAS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SPRING"."DETALLE_VENTAS_PK" ON "SPRING"."DETALLE_VENTAS" ("IDVENTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "TBS_SPRING" ;
--------------------------------------------------------
--  DDL for Index EMPLEADOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SPRING"."EMPLEADOS_PK" ON "SPRING"."EMPLEADOS" ("IDEMPLEADO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "TBS_SPRING" ;
--------------------------------------------------------
--  DDL for Index PRODUCTOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SPRING"."PRODUCTOS_PK" ON "SPRING"."PRODUCTOS" ("IDPRODUCTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "TBS_SPRING" ;
--------------------------------------------------------
--  DDL for Index REGION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SPRING"."REGION_PK" ON "SPRING"."REGIONES" ("IDREGION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "TBS_SPRING" ;
--------------------------------------------------------
--  DDL for Index SUCURSALES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SPRING"."SUCURSALES_PK" ON "SPRING"."SUCURSALES" ("IDSUCURSAL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "TBS_SPRING" ;
--------------------------------------------------------
--  DDL for Index VENTAS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SPRING"."VENTAS_PK" ON "SPRING"."VENTAS" ("IDVENTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "TBS_SPRING" ;
--------------------------------------------------------
--  Constraints for Table SUCURSALES
--------------------------------------------------------

  ALTER TABLE "SPRING"."SUCURSALES" MODIFY ("IDSUCURSAL" NOT NULL ENABLE);
  ALTER TABLE "SPRING"."SUCURSALES" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "SPRING"."SUCURSALES" MODIFY ("IDCOMUNA" NOT NULL ENABLE);
  ALTER TABLE "SPRING"."SUCURSALES" ADD CONSTRAINT "SUCURSALES_PK" PRIMARY KEY ("IDSUCURSAL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "TBS_SPRING"  ENABLE;
--------------------------------------------------------
--  Constraints for Table COMUNA
--------------------------------------------------------

  ALTER TABLE "SPRING"."COMUNA" MODIFY ("IDCOMUNA" NOT NULL ENABLE);
  ALTER TABLE "SPRING"."COMUNA" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "SPRING"."COMUNA" MODIFY ("IDREGION" NOT NULL ENABLE);
  ALTER TABLE "SPRING"."COMUNA" ADD CONSTRAINT "COMUNA_PK" PRIMARY KEY ("IDCOMUNA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "TBS_SPRING"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DETALLE_VENTAS
--------------------------------------------------------

  ALTER TABLE "SPRING"."DETALLE_VENTAS" MODIFY ("IDVENTA" NOT NULL ENABLE);
  ALTER TABLE "SPRING"."DETALLE_VENTAS" MODIFY ("IDPROCUTO" NOT NULL ENABLE);
  ALTER TABLE "SPRING"."DETALLE_VENTAS" MODIFY ("CANTIDAD" NOT NULL ENABLE);
  ALTER TABLE "SPRING"."DETALLE_VENTAS" ADD CONSTRAINT "DETALLE_VENTAS_PK" PRIMARY KEY ("IDVENTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "TBS_SPRING"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EMPLEADOS
--------------------------------------------------------

  ALTER TABLE "SPRING"."EMPLEADOS" MODIFY ("IDEMPLEADO" NOT NULL ENABLE);
  ALTER TABLE "SPRING"."EMPLEADOS" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "SPRING"."EMPLEADOS" MODIFY ("APEPAT" NOT NULL ENABLE);
  ALTER TABLE "SPRING"."EMPLEADOS" MODIFY ("APEMAT" NOT NULL ENABLE);
  ALTER TABLE "SPRING"."EMPLEADOS" MODIFY ("IDSUCURSAL" NOT NULL ENABLE);
  ALTER TABLE "SPRING"."EMPLEADOS" ADD CONSTRAINT "EMPLEADOS_PK" PRIMARY KEY ("IDEMPLEADO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "TBS_SPRING"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CLIENTES
--------------------------------------------------------

  ALTER TABLE "SPRING"."CLIENTES" MODIFY ("IDCLIENTE" NOT NULL ENABLE);
  ALTER TABLE "SPRING"."CLIENTES" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "SPRING"."CLIENTES" MODIFY ("APEPAT" NOT NULL ENABLE);
  ALTER TABLE "SPRING"."CLIENTES" MODIFY ("APEMAT" NOT NULL ENABLE);
  ALTER TABLE "SPRING"."CLIENTES" MODIFY ("IDCOMUNA" NOT NULL ENABLE);
  ALTER TABLE "SPRING"."CLIENTES" MODIFY ("TELEFONO" NOT NULL ENABLE);
  ALTER TABLE "SPRING"."CLIENTES" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "SPRING"."CLIENTES" ADD CONSTRAINT "CLIENTES_PK" PRIMARY KEY ("IDCLIENTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "TBS_SPRING"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRODUCTOS
--------------------------------------------------------

  ALTER TABLE "SPRING"."PRODUCTOS" MODIFY ("IDPRODUCTO" NOT NULL ENABLE);
  ALTER TABLE "SPRING"."PRODUCTOS" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "SPRING"."PRODUCTOS" MODIFY ("PRECIO" NOT NULL ENABLE);
  ALTER TABLE "SPRING"."PRODUCTOS" MODIFY ("STOCK" NOT NULL ENABLE);
  ALTER TABLE "SPRING"."PRODUCTOS" MODIFY ("IDCATEGORIA" NOT NULL ENABLE);
  ALTER TABLE "SPRING"."PRODUCTOS" ADD CONSTRAINT "PRODUCTOS_PK" PRIMARY KEY ("IDPRODUCTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "TBS_SPRING"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CATEGORIAS
--------------------------------------------------------

  ALTER TABLE "SPRING"."CATEGORIAS" MODIFY ("IDCATEGORIA" NOT NULL ENABLE);
  ALTER TABLE "SPRING"."CATEGORIAS" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "SPRING"."CATEGORIAS" ADD CONSTRAINT "CATEGORIAS_PK" PRIMARY KEY ("IDCATEGORIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "TBS_SPRING"  ENABLE;
--------------------------------------------------------
--  Constraints for Table REGIONES
--------------------------------------------------------

  ALTER TABLE "SPRING"."REGIONES" MODIFY ("IDREGION" NOT NULL ENABLE);
  ALTER TABLE "SPRING"."REGIONES" MODIFY ("DESCRICPION" NOT NULL ENABLE);
  ALTER TABLE "SPRING"."REGIONES" ADD CONSTRAINT "REGION_PK" PRIMARY KEY ("IDREGION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "TBS_SPRING"  ENABLE;
--------------------------------------------------------
--  Constraints for Table VENTAS
--------------------------------------------------------

  ALTER TABLE "SPRING"."VENTAS" MODIFY ("IDVENTA" NOT NULL ENABLE);
  ALTER TABLE "SPRING"."VENTAS" MODIFY ("IDEMPLEADO" NOT NULL ENABLE);
  ALTER TABLE "SPRING"."VENTAS" MODIFY ("IDCLIENTE" NOT NULL ENABLE);
  ALTER TABLE "SPRING"."VENTAS" MODIFY ("FECHA" NOT NULL ENABLE);
  ALTER TABLE "SPRING"."VENTAS" ADD CONSTRAINT "VENTAS_PK" PRIMARY KEY ("IDVENTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "TBS_SPRING"  ENABLE;
